### PR TITLE
feat: add tracing support.

### LINKED ISSUE #8: Introduce tracing to improve debugging
The library currently doesn't utilize any form of logging. The tokio project [has a crate](https://github.com/tokio-rs/tracing) that introduces tracing which seems like a reasonable solution considering most consumers are likely already using the tokio runtime. It's also well-integrated with other logging crates for choose-your-adventure type support.

### PR DESCRIPTION
**Pull request by fourbytes**
Thought I'd take a shot at this one. Closes #8.

I've added spans to every operation I can find, but I haven't added any additional log messages yet.

Looks like it would be good to implement this in the `rustify` crate as well. In `Client::execute` for example.

### CODE REVIEW

**Comment by jmgilman** [comment]
Thanks for this PR :) If you're up for it, I had planned on adding tracing output to the tests as well, using something like [tracing-test](https://docs.rs/tracing-test/0.1.0/tracing_test/) but also open to other suggestions. Otherwise, I'm fine to accept this as-is.

**Comment by fourbytes** [comment]
Sounds good, will add that today.

**Comment by fourbytes** [comment]
How's this? I've instrumented each test and added a couple log messages to get it started.
Using tracing-test at the moment to configure the subscriber, but it couple be easily replaced with an alternative in the future if necessary.

**Comment by jmgilman** [comment]
Awesome, thanks for doing that! Looks like you just need to run `cargo fmt` and I can merge :)

**Comment by fourbytes** [comment]
Done, that should do it.

**Pull request merged**
