### PR TITLE
Support /sys/unseal

### PR DESCRIPTION
**Pull request by sjm42**
I am writing a program to unseal Vault(s) over the API.
For this purpose, I need Unseal support for the API so I made it.

As per my own testing with my own code, unseal works with these changes.

The Vault Unseal API doc can be found here:
https://www.vaultproject.io/api-docs/system/unseal

Thanks & sorry  :-)

### CODE REVIEW

**Comment by jmgilman** [comment]
Thanks for your contribution! Would you be open to writing a test for it? Should be able to add it after [this line](https://github.com/jmgilman/vaultrs/blob/master/tests/sys.rs#L42). The [test server](https://github.com/jmgilman/dockertest-server/blob/master/src/servers/hashi/vault.rs#L90) already has the generated token stored, so it should just be a matter of calling the new unseal function with the existing token.

**Comment by sjm42** [comment]
Well, cannot make any promises but I won't refuse right away. I have to take a look at those tests, or can you already hint at what would be the easiest way to get hold of the unseal key(s) to actually test seal/unseal?

**Comment by sjm42** [comment]
Uhm, it is not so simple. Sealing and unsealing vault is not done using auth token but using the unseal key(s). Furthermore, the Vault dev server documentation explicitly is telling this:

"The dev server stores all its data in-memory (but still encrypted), listens on localhost without TLS, and automatically unseals and shows you the unseal key and root access key."

"Insecure operation: Do not run a Vault dev server in production. This approach is only used here to simplify the unsealing process for this demonstration."

Well... using dev server for testing seal/unseal migh be useless. At least I have to check if dev server even honors seal/unseal commands or are they just no-ops that always succeed no matter what.

**Comment by jmgilman** [comment]
Ah, I mistakenly thought the dev server used the root token as the unseal key as well. No worries, I'll merge it as is and look into adding a test in the future. Thanks again!

**Pull request merged**
